source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

pod 'HanekeSwift'

pod 'ObjectMapper'

pod 'PureLayout'

pod 'Socket.IO-Client-Swift'

pod 'SwiftyJSON'